Transactions:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.stage}-DB-FS-Transactions
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: accountId
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: accountId
        KeyType: RANGE